import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;

class AppLocalization {
  AppLocalization(this.locale);

  final Locale locale;

  static AppLocalization? of(BuildContext context) {
    return Localizations.of<AppLocalization>(context, AppLocalization);
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'Create Password': 'Create Password',
      "Search Store": "Search Store",
      'language': 'Language',
      'Delivery Address': 'Delivery Address',
      'Invite Friends': 'Invite Friends',
      'Settings': 'Settings',
      'Confirm Password': 'Confirm Password',
      'Enter your password': 'Enter your password',
      'Phone Number': 'Phone Number',
      'Terms & Conditions': 'Terms & Conditions',
      'By Continue you' '\'re agreed to our':
          'By Continue you' '\'re agreed to our',
      'Continue': 'Continue',
      'Login': 'Login',
      'Enter- your emails and password': 'Enter your emails and password',
      'Forgot password?': 'Forgot password ?',
      'Don\'t have an account?': 'Don\'t have an account?',
      'Signup': 'Signup',
      'Sign Up': 'Sign Up',
      'Email': 'Email',
      'Password': 'Password',
      'credential': 'Haven' '\'t you registered yet ?',
      'User': 'Username',
      'Having?': 'Already have an account ?',
      'Sign in': 'Sign in',
      'Banner': 'Fresh Vegetables',
      'Exclusive Order': 'Exclusive Order',
      'Best Sell': 'Best Selling',
      'Groceries': 'Groceries',
      'Find Products': 'Find Products',
      'My Cart': 'My Cart',
      'My Favourites': 'My Favourites',
      'check': 'Go To Check Out',
      'Log Out': 'Log Out',
      'Oil & Rice': 'Oil & Rice',
      'Beverages': 'Beverages',
      'Drinks': 'Drinks',
      'My Orders': 'My Orders',
      'My orders': 'Orders',
      'my details': 'My Details',
      'delivery access': 'Delivery Aceess',
      'Payment Methods': 'Payment Methods',
      'Promo Card': 'Promo Card',
      'Notifications': 'Notifications',
      'Help': 'Help',
      'About': 'About',
      'Masala & Premix': 'Masala & Premix',
      'Biscuits & Toasts': 'Biscuits & Toasts',
      'Snacks': 'Snacks',
      'cleaning': 'Cleaning',
      'Personal Care': 'Personal Care',
      'Grooming': 'Glooming',
      'Health': 'Health',
      'Baby Care': 'Baby Care',
      'Home needs': 'Home Needs',
      'Home Appliances': 'Home Appliances',
      'No Favorite Items': 'No Favorite Items',
      'Enter Phone Number': 'Enter Phone Number',
      'Full Name': 'Full Name',
      'Terms of Services': 'Terms of Services'
    },
    'ml': {
      'My Orders': 'എന്റെ ഉത്തരവുകൾ',
      "Search Store": "തിരയൽ സ്റ്റോർ",
      'language': 'ഭാഷ',
      'Terms of Services': 'സേവന നിബന്ധനകൾ',
      'Create Password': 'പാസ്‌വേഡ് സൃഷ്‌ടിക്കുക',
      'Delivery Address': 'ഡെലിവറി വിലാസം',
      'Invite Friends': 'സുഹൃത്തുക്കളെ ക്ഷണിക്കുക',
      'Settings': 'ക്രമീകരണങ്ങൾ',
      'Confirm Password': 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      'Enter your password': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
      'Phone Number': 'ഫോൺ നമ്പർ',
      'Terms & Conditions': 'ഉപാധികളും നിബന്ധനകളും',
      'By Continue you' '\'re agreed to our':
          'തുടരുന്നതിലൂടെ നിങ്ങൾ ഞങ്ങളോട് യോജിച്ചു',
      'Continue': 'തുടരുക',
      'Login': 'ലോഗിൻ',
      'Enter- your emails and password':
          'നിങ്ങളുടെ ഇമെയിലുകളും പാസ്‌വേഡും നൽകുക',
      'Forgot password?': 'പാസ്വേഡ് മറന്നോ ?',
      'Don\'t have an account?': 'ഒരു അക്കൗണ്ട് ഇല്ലേ?',
      'Signup': 'സൈൻ അപ്പ് ചെയ്യുക',
      'Sign Up': 'സൈൻ അപ്പ് ചെയ്യുക',
      'Email': 'ഇമെയിൽ',
      'Password': 'രഹസ്യ കോഡ്‌',
      'credential': 'നിങ്ങൾ ഇതുവരെ രജിസ്റ്റർ ചെയ്തിട്ടില്ലേ?',
      'User': 'തുടരാനുള്ള ഉപയോക്തൃനാമം',
      'Having?': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?',
      'Sign in': 'അടയാളം',
      'Banner': 'പുതിയ പച്ചക്കറികൾ',
      'Exclusive Order': 'പ്രത്യേക ഓർഡർ',
      'Best Sell': 'മികച്ച വിൽപ്പന',
      'Groceries': 'പലചരക്ക് സാധനങ്ങൾ',
      'Find Products': 'ഉൽപ്പന്നം കണ്ടെത്തുക',
      'My Cart': 'എന്റെ വണ്ടി',
      'My Favourites': 'എന്റെ പ്രിയപ്പെട്ടവ',
      'check': 'ചെക്ക് ഔട്ട് ചെയ്യാൻ പോകുക',
      'Log Out': 'പുറത്തുകടക്കുക',
      'Masala & Premix': 'മസാലയും പ്രീമിക്സും',
      'Oil & Rice': 'എണ്ണയും അരിയും',
      'Beverages': 'പാനീയങ്ങൾ',
      'orders': 'ഉത്തരവുകൾ',
      'my details': 'എന്റെ വിശദാംശങ്ങൾ',
      'Delivery Access': ' ഡെലിവറി ആക്സസ്',
      'Payment Methods': 'പേയ്മെന്റ് രീതികൾ',
      'Promo Card': 'പ്രൊമോ കാർഡ്',
      'Notifications': 'അറിയിപ്പുകൾ',
      'Help': 'സഹായം',
      'About': 'കുറിച്ച്',
      'Drinks': 'പാനീയങ്ങൾ',
      'Biscuits & Toasts': 'ബിസ്കറ്റും ടോസ്റ്റും',
      'Snacks': 'ലഘുഭക്ഷണം',
      'cleaning': 'വൃത്തിയാക്കൽ',
      'Personal Care': 'സ്വകാര്യ പരിരക്ഷ',
      'Grooming': 'ചമയം',
      'Health': 'ആരോഗ്യം',
      'Baby Care': 'ശിശു സംരക്ഷണം',
      'Home needs': 'വീട്ടാവശ്യങ്ങൾ',
      'Home Appliances': 'വീട്ടുപകരണങ്ങൾ',
      'No Favorite Items': 'പ്രിയപ്പെട്ട ഇനങ്ങളൊന്നുമില്ല',
      'Enter Phone Number': 'ഫോൺ നമ്പർ നൽകുക',
      'Full Name': 'പൂർണ്ണമായ പേര്'
    },
    'hi': {
      'My Orders': 'मेरे आदेश',
      "Search Store": "खोज स्टोर",
      'language': 'भाषा',
      'Terms of Services': 'सेवाओं की शर्तें',
      'Create Password': 'पासवर्ड बनाएं',
      'Delivery Address': 'डिलिवरी का पता',
      'Invite Friends': 'मित्रों को आमंत्रित करें',
      'Settings': 'समायोजन',
      'Confirm Password': 'पासवर्ड की पुष्टि कीजिये',
      'Enter your password': 'अपना कूटशब्द भरें',
      'Phone Number': 'फ़ोन नंबर',
      'Terms & Conditions': 'नियम और शर्तें',
      'By Continue you' '\'re agreed to our':
          'தொடர்வதன் மூலம் நீங்கள்தேடல் கடை எங்களுடையதை ஒப்புக்கொண்டீர்கள்',
      'Continue': 'जारी रखना',
      'Login': 'लॉग इन करें',
      'Enter- your emails and password': 'अपने ईमेल और पासवर्ड दर्ज करें',
      "Forgot password?": 'पासवर्ड भूल गए ?',
      'Don\'t have an account?': 'खाता नहीं है?',
      'Signup': 'साइन अप करें',
      'Sign Up': 'साइन अप करें',
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'credential': 'क्या आपने अभी तक पंजीकरण नहीं कराया है?',
      'User': 'उपयोगकर्ता नाम जारी रखने के लिए',
      'Having?': 'क्या आपके पास पहले से एक खाता मौजूद है',
      'Sign in': 'संकेत',
      'Banner': 'ताज़ी सब्जियां',
      'Exclusive Order': 'अनन्य आदेश',
      'Best Sell': 'सर्वश्रेष्ठ बिक्री',
      'Groceries': 'किराने का सामान',
      'Find Products': 'उत्पाद खोजें',
      'My Cart': 'मेरी गाड़ी',
      'My Favourites': 'मेरा पसंदीदा',
      'check': 'परिक्षण के लिए जाएं',
      'Log Out': 'लॉग आउट',
      'Masala & Premix': 'मसाला और प्रीमिक्स',
      'Oil & Rice': 'तेल और चावल',
      'Beverages': 'पेय',
      'orders': 'आदेश',
      'my details': 'मेरे विवरण',
      'Delivery Access': 'वितरण पहुँच',
      'Payment Methods': 'भुगतान की विधि',
      'Promo Card': 'प्रोमो कार्ड',
      'Notifications': 'सूचनाएं',
      'Help': 'मदद',
      'About': 'के बारे में',
      'Drinks': 'पेय',
      'Biscuits & Toasts': 'बिस्कुट और टोस्ट',
      'Snacks': 'नाश्ता',
      'cleaning': 'सफाई',
      'Personal Care': 'व्यक्तिगत देखभाल',
      'Grooming': 'ग्रूमिंग',
      'Health': 'स्वास्थ्य',
      'Baby Care': 'शिशु के देखभाल',
      'Home needs': 'घर की जरूरतें',
      'Home Appliances': 'घरेलू उपकதேடல் கடைरण',
      'No Favorite Items': 'कोई पसंदीदा आइटम नहीं',
      'Enter Phone Number': 'फोन नंबर दर्ज',
      'Full Name': 'पूरा नाम'
    },
    'ta': {
      'My Orders': 'என் கட்டளைகள்',
      "Search Store": "தேடல் கடை",
      'language': 'மொழி',
      'Settings': 'அமைப்புகள்',
      'Terms of Services': 'சேவை விதிமுறைகள்',
      'Create Password': 'கடவுச்சொல்லை உருவாக்கு',
      'Delivery Address': 'விநியோக முகவரி',
      'Invite Friends': 'நண்பர்களை அழைக்க',
      'Confirm Password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'Enter your password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'Phone Number': 'தொலைபேசி எண்',
      'Terms & Conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'By Continue you' '\'re agreed to our':
          'தொடர்வதன் மூலம் நீங்கள் எங்களுடையதை ஒப்புக்கொண்டீர்கள்',
      'Continue': 'தொடரவும்',
      'Login': 'உள்நுழைய',
      'Enter- your emails and password':
          'உங்கள் மின்னஞ்சல்கள் மற்றும் கடவுச்சொல்லை உள்ளிடவும்',
      "Forgot password?": 'கடவுச்சொல்லை மறந்துவிட்டீர்களா ?',
      'Don\'t have an account?': 'கணக்கு இல்லையா?',
      'Signup': 'பதிவு செய்யவும்',
      'Sign Up': 'பதிவு செய்யவும்',
      'Email': 'மின்னஞ்சல்',
      'Password': 'கடவுச்சொல்',
      'credential': 'நீங்கள் இன்னும் பதிவு செய்யவில்லையா?',
      'User': 'தொடர பயனர்பெயர்',
      'Having?': 'ஏற்கனவே ஒரு கணக்கு உள்ளதா? தமிழ்',
      'Sign in': "அடையாளம்",
      'Banner': 'புதிய காய்கறிகள்',
      'Exclusive Order': 'பிரத்தியேக ஒழுங்கு',
      'Best Sell': 'சிறந்த விற்பனை',
      'Groceries': 'மளிகை',
      'Find Products': 'பொருட்கள் கண்டுபிடிக்க',
      'My Cart': 'என் வண்டி',
      'My Favourites': 'எனக்கு பிடித்தவை',
      'check': 'சென்று பார்க்க',
      'Log Out': 'வெளியேறு',
      'Masala & Premix': 'மசாலா மற்றும் ப்ரீமிக்ஸ்',
      'Oil & Rice': 'எண்ணெய் மற்றும் அரிசி',
      'Beverages': 'பானங்கள்',
      'orders': 'மேலிட உத்தரவுகள்',
      'my details': 'என் விவரங்கள்',
      'Delivery Access': 'விநியோக அணுகல்',
      'Payment Methods': 'பணம் செலுத்தும் முறைகள்',
      'Promo Card': 'விளம்பர அட்டை',
      'Notifications': 'அறிவிப்புகள்',
      'Help': 'உதவி',
      'About': 'பற்றி',
      'Drinks': 'பானங்கள்',
      'Biscuits & Toasts': 'பிஸ்கட் மற்றும் சிற்றுண்டி',
      'Snacks': 'தின்பண்டங்கள்',
      'cleaning': 'சுத்தம்',
      'Personal Care': 'தனிப்பட்ட பாதுகாப்பு',
      'Grooming': 'சீர்ப்படுத்துதல்',
      'Health': 'ஆரோக்கியம்',
      'Baby Care': 'குழத்தை நலம்',
      'Home needs': 'வீட்டு தேவைகள்',
      'Home Appliances': 'வீட்டு உபகரணங்கள்',
      'No Favorite Items': 'பிடித்த பொருட்கள் இல்லை',
      'Enter Phone Number': 'தொலைபேசி எண்ணை உள்ளிடவும்',
      'Full Name': 'முழு பெயர்'
    },
    'gu': {
      'My Orders': 'મારા ઓર્ડર',
      "Search Store": "શોધ સ્ટોર",
      'language': 'ભાષા',
      'Settings': 'સેટિંગ્સ',
      'Terms of Services': 'સેવાઓની શરતો',
      'Create Password': 'પાસવર્ડ બનાવો',
      'Delivery Address': 'વિતરણ સરનામું',
      'Invite Friends': 'મિત્રોને આમંત્રિત કરો',
      'Confirm Password': 'પાસવર્ડની પુષ્ટિ કરો',
      'Enter your password': 'તમારો પાસવર્ડ નાખો',
      'Phone Number': 'ફોન નંબર',
      'Terms & Conditions': 'નિયમો અને શરત',
      'By Continue you' '\'re agreed to our':
          'ચાલુ રાખીને તમે અમારી સાથે સંમત થાઓ છો',
      'Continue': 'ચાલુ રાખો',
      'Login': 'પ્રવેશ કરો',
      'Enter- your emails and password': 'તમારા ઇમેઇલ્સ અને પાસવર્ડ દાખલ કરો',
      'Forgot password?': 'પાસવર્ડ ભૂલી ગયા છો?',
      'Don\'t have an account?': 'તમારી પાસે ખાતું નથી?',
      'Signup': 'સાઇનઅપ કરો',
      'Sign Up': 'સાઇન અપ કરો',
      'Email': 'ઈમેલ',
      'Password': 'પાસવર્ડ',
      'credential': 'તમે હજુ સુધી નોંધણી કરાવી નથી?',
      'User': 'વપરાશકર્તા નામ',
      'Having?': 'પહેલેથી એકાઉન્ટ છે?,',
      'Sign in': 'સાઇન ઇન કરો',
      'Banner': 'તાજા શાકભાજી',
      'Exclusive Order': 'વિશિષ્ટ ઓર્ડર',
      'Best Sell': 'બેસ્ટ સેલિંગ',
      'Groceries': 'કરિયાણા',
      'Find Products': 'ઉત્પાદનો શોધો',
      'My Cart': 'મારી કાર્ટ',
      'My Favourites': 'મારા મનપસંદ',
      'check': 'ચેક આઉટ પર જાઓ',
      'Log Out': 'લૉગ આઉટ',
      'Masala & Premix': 'મસાલા અને પ્રિમિક્સ',
      'Oil & Rice': 'તેલ અને ચોખા',
      'Beverages': 'પીણાં',
      'orders': 'ઓર્ડર',
      'my details': 'મારી વિગતો',
      'delivery access': 'ડિલિવરી ઍક્સેસ',
      'Payment Methods': 'ચુકવણી પદ્ધતિઓ',
      'Promo Card': 'પ્રોમો કાર્ડ',
      'Notifications': 'સૂચનાઓ',
      'Help': 'મદદ',
      'About': 'વિશે',
      'Drinks': 'પીણાં',
      'Biscuits & Toasts': 'બિસ્કીટ અને ટોસ્ટ',
      'Snacks': 'નાસ્તો',
      'cleaning': 'સફાઈ',
      'Personal Care': 'વ્યક્તિગત સંભાળ',
      'Grooming': 'માવજત',
      'Health': 'આરોગ્ય',
      'Baby Care': 'બાળકની સારસંભાળ',
      'Home needs': 'ઘરની જરૂરિયાતો',
      'Home Appliances': 'ઘરેલું ઉપકરણો',
      'No Favorite Items': 'કોઈ મનપસંદ વસ્તુઓ નથી',
      'Enter Phone Number': 'ફોન નંબર દાખલ કરો',
      'Full Name': 'પૂરું નામ'
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]![key] ?? '** $key not found';
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<AppLocalization> {
  const AppLocalizationDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ml', 'hi', 'ta', 'gu'].contains(locale.languageCode);

  @override
  Future<AppLocalization> load(Locale locale) {
    return SynchronousFuture<AppLocalization>(
      AppLocalization(locale),
    );
  }

  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
}
